
title: RVML Designing
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
description: >- # this means to ignore newlines until "baseurl:"
  My portfolio
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "https://rvmldesigning.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: ahmadajmi/type
plugins:
  - jekyll-remote-theme

github:
 is_project_page: false

markdown: kramdown

kramdown:
  parse_block_html: true
  highlighter: none

carousels:



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
